# Generated by Django 6.0.1 on 2026-02-01 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(help_text="Brief description of this school's approach (1-2 sentences)")),
                ('color', models.CharField(default='#3498db', help_text='Hex color code for UI display', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('introduction', models.TextField(help_text='Neutral introduction to this topic (Tier 2 content)')),
                ('tier', models.IntegerField(choices=[(1, 'Approved Reference Content'), (2, 'Resource-Informed Platform Content'), (3, 'Generative On-Demand Content')], default=2)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('lesson_plan', 'Lesson Plan'), ('discussion', 'Discussion Questions'), ('flashcards', 'Flashcards'), ('assessment', 'Assessment'), ('slides', 'Slides'), ('infographic', 'Infographic')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(help_text='Content in Markdown format (for web display)')),
                ('file', models.FileField(blank=True, help_text='Optional downloadable file (PDF, etc.)', null=True, upload_to='materials/')),
                ('tier', models.IntegerField(choices=[(1, 'Approved Reference Content'), (2, 'Resource-Informed Platform Content'), (3, 'Generative On-Demand Content')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='topics.topic')),
            ],
            options={
                'ordering': ['material_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The comparison question, e.g., 'What causes inflation?'", max_length=300)),
                ('description', models.TextField(blank=True, help_text='Additional context about this comparison dimension')),
                ('points_of_agreement', models.TextField(blank=True, help_text='What schools agree on regarding this question')),
                ('key_divergence', models.TextField(blank=True, help_text='The main points of disagreement')),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_questions', to='topics.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_type', models.CharField(choices=[('overview', 'Overview'), ('debate', 'Debate'), ('lecture', 'Lecture')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('script', models.TextField(help_text='The text script used to generate this audio')),
                ('audio_file', models.FileField(blank=True, help_text='Generated audio file', null=True, upload_to='audio/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('tier', models.IntegerField(choices=[(1, 'Approved Reference Content'), (2, 'Resource-Informed Platform Content'), (3, 'Generative On-Demand Content')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_content', to='topics.topic')),
            ],
            options={
                'verbose_name_plural': 'Audio content',
                'ordering': ['audio_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SchoolPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_summary', models.CharField(help_text='Short summary for comparison tables', max_length=300)),
                ('detailed_position', models.TextField(blank=True, help_text="Longer explanation of this school's position")),
                ('critique_of_others', models.TextField(blank=True, help_text="This school's critique of other perspectives")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='topics.comparisonquestion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='topics.school')),
            ],
            options={
                'ordering': ['school__order'],
                'unique_together': {('question', 'school')},
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'The Neoclassical View: Inflation as a Demand and Expectations Problem'", max_length=300)),
                ('content', models.TextField(help_text='Full explanation in Markdown format')),
                ('core_idea', models.TextField(blank=True, help_text='Brief summary of the core argument')),
                ('key_figures', models.TextField(blank=True, help_text='Notable economists associated with this view')),
                ('strengths', models.TextField(blank=True, help_text='Acknowledged strengths of this perspective')),
                ('limitations', models.TextField(blank=True, help_text='Acknowledged limitations and critiques')),
                ('tier', models.IntegerField(choices=[(1, 'Approved Reference Content'), (2, 'Resource-Informed Platform Content'), (3, 'Generative On-Demand Content')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='topics.school')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='topics.topic')),
            ],
            options={
                'ordering': ['school__order'],
                'unique_together': {('topic', 'school')},
            },
        ),
    ]
