# Generated by Django 6.0.1 on 2026-02-01 16:54

from django.db import migrations


def load_schools(apps, schema_editor):
    School = apps.get_model('topics', 'School')

    schools = [
        {
            'name': 'Neoclassical',
            'slug': 'neoclassical',
            'short_description': 'The mainstream view treating inflation as a demand-supply imbalance, managed through central bank interest rate policy and inflation targeting.',
            'color': '#3498db',  # Blue
            'order': 1,
        },
        {
            'name': 'Monetarist',
            'slug': 'monetarist',
            'short_description': 'Inflation is always and everywhere a monetary phenomenon—caused by money supply growing faster than output.',
            'color': '#2ecc71',  # Green
            'order': 2,
        },
        {
            'name': 'Austrian',
            'slug': 'austrian',
            'short_description': 'Credit expansion through the banking system distorts interest rates and price signals, leading to malinvestment and inflation.',
            'color': '#f39c12',  # Orange
            'order': 3,
        },
        {
            'name': 'Post-Keynesian',
            'slug': 'post-keynesian',
            'short_description': 'Inflation arises from cost pressures and distributional conflict between workers, firms, and other groups competing for shares of output.',
            'color': '#e74c3c',  # Red
            'order': 4,
        },
        {
            'name': 'MMT',
            'slug': 'mmt',
            'short_description': 'Modern Monetary Theory sees inflation as spending exceeding the economy\'s real productive capacity, controlled through fiscal policy.',
            'color': '#9b59b6',  # Purple
            'order': 5,
        },
        {
            'name': 'Ecological',
            'slug': 'ecological',
            'short_description': 'Biophysical constraints on growth and resource depletion create inflationary pressures that monetary policy cannot address.',
            'color': '#1abc9c',  # Teal
            'order': 6,
        },
    ]

    for school_data in schools:
        School.objects.create(**school_data)


def remove_schools(apps, schema_editor):
    School = apps.get_model('topics', 'School')
    School.objects.filter(slug__in=[
        'neoclassical', 'monetarist', 'austrian',
        'post-keynesian', 'mmt', 'ecological'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_schools, remove_schools),
    ]
